package euler2;

public class Main {

	public static void main(String[] args) {
		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous
		 * two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 1,2,3,5,8,13,21,34,55,89,... By considering the terms in the Fibonacci
		 * sequence whose values do not exceed four million, find the sum of the
		 * even-valued terms.
		 */

		int seqsum = 0;
		int fibNum1 = 1;
		int fibNum2 = 2;
		int oldFibNum1;

		for (int i = 0; i < 4000000; i = fibNum2) {
			if (fibNum2 % 2 == 0) {
				seqsum = seqsum + fibNum2;
			}
			oldFibNum1 = fibNum1;
			fibNum1 = fibNum2;
			fibNum2 = oldFibNum1 + fibNum2;

		}

		System.out.println(seqsum);

	}

}
